// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Block = require("bs-platform/lib/js/block.js");
var Caml_format = require("bs-platform/lib/js/caml_format.js");

function evaluate(expr) {
  switch (expr.tag | 0) {
    case 0 : 
        return Caml_format.caml_int_of_string(expr[0]);
    case 1 : 
        return evaluate(expr[0]) + evaluate(expr[1]) | 0;
    case 2 : 
        return evaluate(expr[0]) - evaluate(expr[1]) | 0;
    
  }
}

var expr = /* Minus */Block.__(2, [
    /* Add */Block.__(1, [
        /* Digital */Block.__(0, ["3"]),
        /* Digital */Block.__(0, ["5"])
      ]),
    /* Digital */Block.__(0, ["3"])
  ]);

console.log(evaluate(expr));

exports.evaluate = evaluate;
exports.expr = expr;
/*  Not a pure module */
